<HubBtn>:
    canvas.before:
        Color:
            rgba: 1, 0, 0, 1
        Line:
            width: 5
            rectangle: self.x, self.y, self.width, self.height
    size: self.texture_size

<PLScareManager>:
    FirstScreen:
    SecondScreen:
    ThirdScreen:

<FirstScreen>:
    name: '_first_screen_'

<SecondScreen>:
    name: '_second_screen_'

<ThirdScreen>:
    name: '_third_screen_'